# Generated by Django 5.1 on 2024-08-21 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_game_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='review',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
